site_name: SoeiroTech Django Boilerplate
site_url: ""
docs_dir: ../docs
site_dir: ../site

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: slate
      primary: deep purple
      accent: indigo
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy

plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - tables
  - toc:
      permalink: true

nav:
  - Inicio: index.md
  - Engenharia de Software: engenharia-software.md
  - Roadmap: roadmap.md
  - Backend:
      - Arquitetura: backend/arquitetura.md
      - APIs: backend/apis.md
      - Models: backend/models.md
